spring:
  application:
    name: online-judge-judge-service
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  #  session:
  #    store-type: redis
  #    # 30 天过期
  #    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.189.158:3306/online_judge
    username: name
    password: password
  Redis:
    host: 192.168.189.158
    port: 6379
    password:
    database: 1
    timeout: 6000        # 超时时间
    lettuce:
      pool:
        max-active: 8         # 连接池最大连接数（使用负值表示没有限制），默认为8
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制），默认为-1
        max-idle: 10           # 连接池中的最大空闲连接，默认为10
        min-idle: 2        # 连接池中的最小空闲连接，默认为0
  session:
    # 30
    timeout: 2592000
#    store-type: redis
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    username: guest

  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true
server:
  address: 0.0.0.0
  port: 8109
  servlet:
    context-path: /api/judge
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    cache-enabled: false
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
codesandbox:
  type: remote
knife4j:
  enable: true